stages:
- stage: A
  jobs:
  - job: myJob1
    displayName: My Job-1
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'
- stage: B
  jobs:
  - job: myJob2
    displayName: My Job-2
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'
- stage: C
  dependsOn: 
  - A
  - B
  jobs:
  - job: myJob2
    displayName: My Job-2
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'