jobs:
- job: Job1
  steps:
  - script: echo Hello, world!
- job: Job2
  dependsOn: Job1 
  steps:
  - script: echo Hello, world!
- job: Job3
  dependsOn: Job1
  steps:
  - script: echo Hello, world!
- job: Job4
  dependsOn: 
  - Job2
  - Job3
  steps:
  - script: echo Hello, world!