https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=example%2Cparameter-schema#triggers
# Push based triggers

#short syntax
trigger:
- master
- releases/*

# disable push trigger
trigger: none


# full syntax
trigger:
  batch: true # batch changes if true; start a new build for every push if false (default)
  branches:
    include:
    - features/*
    exclude:
    - features/experimental/*
  paths:
    exclude:
    - README.md
  tags:
    include:
    - goodToGo







