
variables: 
 system.debug: 'true'

resources:
  repositories:
  - repository: common
    type: github
    name: raiyanalam/InfinityShell
    endpoint: AzureDevOpsDemo

jobs:
-  job: job1
   steps:
   - script: |
       echo  $(Build.Repository.LocalPath)
       cd $(Build.Repository.LocalPath)
       ls -ltr