# your ci pipeline: https://releasemanagementpm.visualstudio.com/vmdemo/_build?definitionId=302&_a=summary
# triggered pipeline: https://releasemanagementpm.visualstudio.com/AzureDevOpsDemo/_build/results?buildId=70546&view=results

variables: 
 system.debug: 'true'
 skipComponentGovernanceDetection: 'true'

resources:
- container: mycontainer
  image: myprivate.azurecr.io/windowsservercore:1803
  endpoint: my_acr_connection

jobs:
-  job: job1
   steps:
   - script: |
       cd $(Pipeline.Workspace)
       ls -ltr
       cd $(Pipeline.Workspace)/MyCIPipeline
       ls -ltr
      