# template Repo: https://github.com/raiyanalam/Infinity-Shell/tree/master/templates

resources:
  repositories:
    - repository: templateRepo
      type: github
      name: raiyanalam/Infinity-Shell

jobs:
- template: cross-repo-template.yml@templateRepo  # Template reference
