stages:
- stage: deploy
  jobs:
  - deployment: DeployWeb
    displayName: deploy Web App
    pool:
      vmImage: 'Ubuntu-latest'    
    environment: 'dev' # creates empty environment if it doesn't exist
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo 'deploy my web app!'