jobs:
- job: Job1
  steps:
  - script: echo Hello, world!
- job: remediation_job
  dependsOn: Job1 
  condition: failed('Job1')
  steps:
  - script: echo run remediation script
  # succeeded(), Only when all previous dependencies have succeeded. 
  # always() will always run, even if the run is canceled
  # succeededOrFailed() Even if a previous dependency has failed, unless the run was canceled
  # and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/users/'))