variables: 
 system.debug: 'true'
 skipComponentGovernanceDetection: 'true'

resources:
  repositories:
  - repository: Infinity_Shell
    type: github
    name: raiyanalam/Infinity-Shell
    endpoint: AzureDevOpsDemo

jobs:
-  job: job1
   steps:
   - checkout: self
   - checkout: Infinity_Shell
   - script: |
       echo  $(Agent.BuildDirectory)
       cd $(Agent.BuildDirectory)/s/Infinity-Shell/
       ls -ltr
       echo "================"
       cat README.md