stages:
- stage: deploy
  jobs:
  - deployment: DeployWeb
    displayName: deploy Web App
    pool:
      vmImage: 'Ubuntu-latest'    
    environment: 
      name: dev # creates empty environment if it doesn't exist
      resourceType: VirtualMachine
    strategy:
      rolling:
        maxParallel: 1  #for percentages, mention as x%
        preDeploy:
          steps:        
          - script: echo initialize, cleanup, backup, install certs
          - checkout: self
        deploy:
          steps:
          - script: echo 'deploy my web app to the machine'
        routeTraffic:
          steps:
          - script: echo routing traffic
        postRouteTraffic:
          steps:
          - script: echo health check post-route traffic
        on:
          failure:
            steps:
            - script: echo Restore from backup! This is on failure
          success:
            steps:
            - script: echo Notify! This is on success