# your ci pipeline: https://releasemanagementpm.visualstudio.com/vmdemo/_build?definitionId=302&_a=summary
# triggered pipeline: https://releasemanagementpm.visualstudio.com/AzureDevOpsDemo/_build/results?buildId=70546&view=results

variables: 
 system.debug: 'true'
 skipComponentGovernanceDetection: 'true'

resources:
  pipelines:    
  - pipeline: MyCIPipeline
    project:  vmdemo
    source: 'raivmdemo - CI'
    trigger: true
#    trigger:
#      branches:
#        include:        
#        - releases/*
#        exclude:
#        - users/*

jobs:
-  job: job1
   steps:
   - download: MyCIPipeline   # pipeline resource identifier.   
     artifact: drop  
   - script: |
       cd $(Pipeline.Workspace)
       ls -ltr
       cd $(Pipeline.Workspace)/MyCIPipeline
       ls -ltr
      