# your ci pipeline: https://releasemanagementpm.visualstudio.com/vmdemo/_build?definitionId=302&_a=summary

variables: 
 system.debug: 'true'
 skipComponentGovernanceDetection: 'true'

resources:
  pipelines:    
  - pipeline: MyCIPipeline
    project:  vmdemo
    source: 'raivmdemo - CI'
#   trigger: true
    trigger:
      branches:
        include:        
        - releases/*
        exclude:
        - users/*

jobs:
-  job: job1
   steps:
   - task: DownloadPipelineArtifact@2
     inputs:
       source: 'specific'
       project: vmdemo
       pipeline: 302
       runVersion: 'latest'
#   - task: downloadPipelineArtifact@2
#     inputs:
#      source: specific
#      pipeline: MyCIPipeline
   - script: |
       cd $(Pipeline.Workspace)
       ls -ltr
       cd $(Pipeline.Workspace)/MyCIPipeline
       ls -ltr
      